export const SET_ITEM = 'SET_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const POST_ITEM = 'POST_ITEM';
export const GET_RELATED_FAILURE = 'GET_RELATED_FAILURE';
export const GET_RELATED_SUCCESS = 'GET_RELATED_SUCCESS';
